CREATE TYPE "ETypeRoles" AS ENUM (
    'ADMIN',
    'USER'
    );

CREATE TYPE "EnumTags" AS ENUM (
    'ENTERTAINMENT',
    'BILLS',
    'FOOD',
    'ELECTRONICS',
    'FUEL',
    'UPKEEP'
    );

CREATE TABLE IF NOT EXISTS "Users" (
                                       "id" BIGINT NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
                                       "username" VARCHAR(25),
    "password" VARCHAR(255),
    "email" VARCHAR(255),
    PRIMARY KEY("id")
    );


CREATE INDEX "Users_index_0"
    ON "Users" ("username", "email");

CREATE TABLE IF NOT EXISTS "Role" (
                                      "id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
                                      "name" VARCHAR(30) NOT NULL,
    "ERole" "ETypeRoles" NOT NULL,
    PRIMARY KEY("id")
    );




CREATE TABLE IF NOT EXISTS "Notes" (
                                       "id" BIGINT NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
                                       "name" VARCHAR(30),
    "description" VARCHAR(255),
    "value" DECIMAL,
    "dateOfCreation" TIMESTAMPTZ,
    "dateOfUpdate" TIMESTAMPTZ,
    PRIMARY KEY("id")
    );


CREATE INDEX "Notes_index_0"
    ON "Notes" ("name", "dateOfCreation");

CREATE TABLE IF NOT EXISTS "Categories" (
                                            "id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
                                            "name" VARCHAR(30) NOT NULL,
    "ETag" "EnumTags" NOT NULL,
    PRIMARY KEY("id")
    );


CREATE INDEX "Categories_index_0"
    ON "Categories" ("name", "ETag");

CREATE TABLE IF NOT EXISTS "Authentication" (
                                                "userid" BIGINT NOT NULL,
                                                "roleid" INTEGER NOT NULL,
                                                "id" BIGINT NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
                                                "updatedAt" TIMESTAMPTZ NOT NULL,
                                                PRIMARY KEY("id")
    );




CREATE TABLE IF NOT EXISTS "Tags" (
                                      "annotationid" BIGINT NOT NULL,
                                      "categoryid" INTEGER NOT NULL,
                                      "id" BIGINT NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
                                      PRIMARY KEY("id")
    );




CREATE TABLE IF NOT EXISTS "UserNotes" (
                                           "userid" BIGINT NOT NULL,
                                           "noteid" BIGINT NOT NULL,
                                           "id" BIGINT NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
                                           PRIMARY KEY("id")
    );



ALTER TABLE "Authentication"
    ADD CONSTRAINT fk_Authentication_userid_Users
        FOREIGN KEY("userid") REFERENCES "Users"("id")
            ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "Authentication"
    ADD CONSTRAINT fk_Authentication_roleid_Role
        FOREIGN KEY("roleid") REFERENCES "Role"("id")
            ON UPDATE CASCADE ON DELETE NO ACTION;
ALTER TABLE "Tags"
    ADD CONSTRAINT fk_Categories_id_Tags
        FOREIGN KEY("categoryid") REFERENCES "Categories"("id")
            ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "Tags"
    ADD CONSTRAINT fk_Tags_annotationid_Annotations
        FOREIGN KEY("annotationid") REFERENCES "Notes"("id")
            ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "UserNotes"
    ADD CONSTRAINT fk_Users_id_UserNotes
        FOREIGN KEY("userid") REFERENCES "Users"("id")
            ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "UserNotes"
    ADD CONSTRAINT fk_Notes_id_UserNotes
        FOREIGN KEY("noteid") REFERENCES "Notes"("id")
            ON UPDATE NO ACTION ON DELETE NO ACTION;