
CREATE TABLE IF NOT EXISTS "VerificationCodes" (
    "id" BIGINT NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
    "userid" BIGINT NOT NULL,
    "code" VARCHAR(7) NOT NULL,
    "type" VARCHAR(50) NOT NULL,
    "expiracy_date" TIMESTAMP NOT NULL,
    "verified" BOOLEAN DEFAULT False,
    "attempts" INTEGER DEFAULT 0,
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "verified_at" TIMESTAMP,
    PRIMARY KEY("id")
    );

CREATE INDEX "idx_verification_codes_userid"
    ON "VerificationCodes" ("userid");
CREATE INDEX "idx_verification_codes_code"
    ON "VerificationCodes" ("code");
CREATE INDEX "idx_verification_codes_type"
    ON "VerificationCodes" ("type");
CREATE INDEX "idx_verification_code_created_at"
    ON "VerificationCodes" ("created_at");

ALTER TABLE "VerificationCodes"
    ADD CONSTRAINT verification_codes_userid
        FOREIGN KEY("userid") REFERENCES "Users"("id")
        ON UPDATE NO ACTION ON DELETE NO ACTION;