CREATE TYPE eTypeRoles AS ENUM (
    'ADMIN',
    'USER'
    );

CREATE TYPE enumTags AS ENUM (
    'ENTERTAINMENT',
    'BILLS',
    'FOOD',
    'ELECTRONICS',
    'FUEL',
    'UPKEEP'
    );

CREATE TABLE IF NOT EXISTS users (
                                     id BIGINT NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
                                     username VARCHAR(25),
                                     password VARCHAR(255),
                                     email VARCHAR(255),
                                     PRIMARY KEY(id)
);

CREATE INDEX users_index_0
    ON users (username, email);

CREATE TABLE IF NOT EXISTS roles (
                                     id INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
                                     name VARCHAR(30) NOT NULL,
                                     erole eTypeRoles NOT NULL,
                                     PRIMARY KEY(id)
);

CREATE TABLE IF NOT EXISTS notes (
                                     id BIGINT NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
                                     name VARCHAR(30),
                                     description VARCHAR(255),
                                     value DECIMAL,
                                     dateofcreation TIMESTAMPTZ,
                                     dateofupdate TIMESTAMPTZ,
                                     PRIMARY KEY(id)
);

CREATE INDEX notes_index_0
    ON notes (name, dateofcreation);

CREATE TABLE IF NOT EXISTS categories (
                                          id INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
                                          name VARCHAR(30) NOT NULL,
                                          etag enumTags NOT NULL,
                                          PRIMARY KEY(id)
);

CREATE INDEX categories_index_0
    ON categories (name, etag);

CREATE TABLE IF NOT EXISTS authentication (
                                              userid BIGINT NOT NULL,
                                              roleid INTEGER NOT NULL,
                                              updatedat TIMESTAMPTZ NOT NULL,
                                              PRIMARY KEY(userid,roleid)
);
ALTER TABLE authentication
    ADD CONSTRAINT fk_Authentication_userid_Users
        FOREIGN KEY(userid) REFERENCES users(id)
            ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE authentication
    ADD CONSTRAINT fk_Authentication_roleid_Role
        FOREIGN KEY(roleid) REFERENCES roles(id)
            ON UPDATE CASCADE ON DELETE NO ACTION;

CREATE TABLE IF NOT EXISTS tags (
                                    noteid BIGINT NOT NULL,
                                    categoryid INTEGER NOT NULL,
                                    PRIMARY KEY(noteid,categoryid)
);

ALTER TABLE tags
    ADD CONSTRAINT fk_Categories_id_Tags
        FOREIGN KEY(categoryid) REFERENCES categories(id)
            ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE tags
    ADD CONSTRAINT fk_Tags_noteid_Annotations
        FOREIGN KEY(noteid) REFERENCES notes(id)
            ON UPDATE NO ACTION ON DELETE NO ACTION;

CREATE TABLE IF NOT EXISTS userNotes (
                                         userid BIGINT NOT NULL,
                                         noteid BIGINT NOT NULL,
                                         PRIMARY KEY(userid,noteid)
);
ALTER TABLE userNotes
    ADD CONSTRAINT fk_Users_id_UserNotes
        FOREIGN KEY(userid) REFERENCES users(id)
            ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE userNotes
    ADD CONSTRAINT fk_Notes_id_UserNotes
        FOREIGN KEY(noteid) REFERENCES notes(id)
            ON UPDATE NO ACTION ON DELETE NO ACTION;