CREATE TYPE authProvider AS ENUM(
    'GOOGLE',
    'FACEBOOK',
    'LOCAL'
);

ALTER TABLE users
    ADD COLUMN IF NOT EXISTS provider authProvider DEFAULT 'LOCAL',
    ADD COLUMN IF NOT EXISTS enabled BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN IF NOT EXISTS providerid VARCHAR(255),
    ADD COLUMN IF NOT EXISTS emailverified BOOLEAN NOT NULL DEFAULT false;