
CREATE TABLE IF NOT EXISTS verification_codes (
    id BIGINT NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
    userid BIGINT NOT NULL,
    code VARCHAR(7) NOT NULL,
    type VARCHAR(50) NOT NULL,
    expiracy_date TIMESTAMP NOT NULL,
    verified BOOLEAN DEFAULT false,
    attempts INTEGER DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    verified_at TIMESTAMP,
    PRIMARY KEY(id)
    );

CREATE INDEX idx_verification_codes_userid ON verification_codes (userid);
CREATE INDEX idx_verification_codes_code ON verification_codes (code);
CREATE INDEX idx_verification_codes_type ON verification_codes (type);
CREATE INDEX idx_verification_code_created_at ON verification_codes (created_at);

ALTER TABLE verification_codes
    ADD CONSTRAINT fk_verification_codes_userid_users
        FOREIGN KEY(userid) REFERENCES users(id)
            ON UPDATE NO ACTION ON DELETE CASCADE;