server{

  listen 80;
  server_name money-flow.app www.money-flow.app;

  location /.well-know/acme-challenge/{
    root /var/www/certbot;
  }

  location / {
  return 200 'aguardando certificado';
  add_header Content-Type text/plain;
  }

}
